from os import getenv


DEBUG = getenv('DEBUG', 'false').lower() == 'true'
SECRET_KEY = getenv('SECRET_KEY', 'Some-Autogenerated-Secret-Key')

ADMIN_URL = getenv('ADMIN_URL', 'admin/')
SUPERUSERS = list(getenv('SUPERUSERS', 'root').split(','))
DEFAULT_PASSWORD = getenv('DEFAULT_PASSWORD', 'password')

DATABASE_HOST = getenv('DATABASE_HOST', '127.0.0.1')
DATABASE_PORT = int(getenv('DATABASE_PORT', '5432'))
DATABASE_NAME = getenv('DATABASE_NAME', 'db_name')
DATABASE_USER = getenv('DATABASE_USER', 'db_user')
DATABASE_PASSWORD = getenv('DATABASE_PASSWORD', 'db_password')

SENTRY = getenv('SENTRY', 'false').lower() == 'true'
DSN = getenv('DSN')

TG_TOKEN = getenv('TG_TOKEN')
TG_DELVELOPER = getenv('TG_DELVELOPER')
