# Generated by Django 3.2.6 on 2021-08-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ensemble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='campus/ensemble/logo', verbose_name='Логотип')),
                ('description', models.TextField(verbose_name='Описание')),
                ('achievements', models.TextField(blank=True, verbose_name='Достижения')),
                ('contacts', models.TextField(verbose_name='Контакты')),
            ],
        ),
    ]
