# Generated by Django 3.2.6 on 2021-08-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0002_alter_ensemble_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensemble',
            name='is_main_page',
            field=models.BooleanField(default=False, verbose_name='Главная страница'),
        ),
    ]
