# Generated by Django 3.2.6 on 2021-08-07 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_name'),
        ('campus_sibsau', '0002_ensemble'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ensemble',
            options={'verbose_name': 'Ансамбль', 'verbose_name_plural': 'Ансамбли'},
        ),
        migrations.CreateModel(
            name='JoiningEnsemble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=31, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=19, verbose_name='Телефон')),
                ('link_on_vk', models.CharField(max_length=128, verbose_name='Ссылка на ВКонтакте')),
                ('experience', models.TextField(verbose_name='Опыт творческой деятельности')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('create_data', models.DateTimeField(auto_now_add=True, verbose_name='Дата вступления')),
                ('ensemble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_sibsau.ensemble', verbose_name='Ансамбль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Пользователь')),
            ],
        ),
    ]
