# Generated by Django 3.2.6 on 2021-08-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0003_ensemble_is_main_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportclub',
            name='phone',
            field=models.CharField(max_length=19, null=True, verbose_name='Телефон тренера'),
        ),
    ]
