# Generated by Django 3.2.1 on 2021-08-08 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0003_auto_20210807_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joiningensemble',
            options={'verbose_name': 'Заявка на вступление в ансамбль', 'verbose_name_plural': 'Заявки на вступление в ансамбли'},
        ),
    ]
