# Generated by Django 3.2.6 on 2021-08-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0004_alter_sportclub_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportclub',
            name='phone',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='Телефон тренера'),
        ),
    ]
