# Generated by Django 3.2.6 on 2021-08-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0005_rename_description_ensemble_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensemble',
            name='logo',
            field=models.ImageField(upload_to='media/campus/ensemble/logo', verbose_name='Логотип'),
        ),
    ]
