# Generated by Django 3.2.1 on 2021-08-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0005_rename_description_ensemble_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensemble',
            name='is_accept_participants',
            field=models.BooleanField(default=True, help_text="Кнопка 'Подать заявку' не будет отбражаться при значнии 'False'", verbose_name='Принимает участников'),
        ),
    ]
