# Generated by Django 3.2.6 on 2021-08-12 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0006_alter_ensemble_logo'),
        ('campus_sibsau', '0006_ensemble_is_accept_participants'),
    ]

    operations = [
    ]
