# Generated by Django 3.2.6 on 2021-08-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0007_merge_20210812_0835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ensemble',
            options={'verbose_name': 'Коллектив', 'verbose_name_plural': 'Коллективы'},
        ),
        migrations.AlterModelOptions(
            name='joiningensemble',
            options={'verbose_name': 'Заявка в коллектив', 'verbose_name_plural': 'Заявки в коллективы'},
        ),
        migrations.RemoveField(
            model_name='ensemble',
            name='is_accept_participants',
        ),
        migrations.AddField(
            model_name='ensemble',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=128, verbose_name='Ссылка на инстаграм'),
        ),
        migrations.AddField(
            model_name='ensemble',
            name='vk_link',
            field=models.CharField(blank=True, max_length=128, verbose_name='Ссылка на вк'),
        ),
        migrations.AlterField(
            model_name='ensemble',
            name='logo',
            field=models.ImageField(upload_to='campus/ensemble/logo', verbose_name='Логотип'),
        ),
    ]
