# Generated by Django 3.2.7 on 2021-10-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0007_faculty_joiningfaculty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JoiningFaculty',
        ),
    ]
