# Generated by Django 3.2.7 on 2021-10-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0008_delete_joiningfaculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='learning',
        ),
    ]
