# Generated by Django 3.2.6 on 2021-08-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0008_auto_20210812_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensemble',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Ссылка на инстаграм'),
        ),
        migrations.AlterField(
            model_name='ensemble',
            name='vk_link',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Ссылка на вк'),
        ),
    ]
