# Generated by Django 3.2.7 on 2021-10-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0009_auto_20211008_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='contacts',
            field=models.URLField(blank=True, null=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=128, null=True, verbose_name='Ссылка на инстаграм'),
        ),
    ]
