version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: django-jazzmin
    versions:
    - 2.4.5
  - dependency-name: djangorestframework
    versions:
    - 3.12.3
    - 3.12.4
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: flake8-bugbear
    versions:
    - 21.3.1
    - 21.3.2
  - dependency-name: pillow
    versions:
    - 8.1.1
    - 8.1.2
  - dependency-name: sentry-sdk
    versions:
    - 0.20.0
    - 0.20.1
    - 0.20.2
    - 0.20.3
    - 1.0.0
  - dependency-name: django
    versions:
    - 3.1.7
  - dependency-name: django-modeltranslation
    versions:
    - 0.16.2
  - dependency-name: cryptography
    versions:
    - 3.3.2
