# Generated by Django 3.1.6 on 2021-02-05 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-views'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
    ]
