repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v4.0.1"
  hooks:
    - id: check-merge-conflict
    - id: debug-statements

- repo: local

  hooks:
    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [python]
      args: [
        # TODO: удалить VNE003
          "--ignore=E501,DJ01,W503,VNE003",
          "--max-line-length=120",
          "--per-file-ignores=tests/*.py:S101"
      ]
