version: "3"
services:
    database:
        container_name: database
        image: postgres:13.4-alpine
        restart: always
        env_file: src/.env
        volumes:
            - ./volumes/db/data:/var/lib/database/data

    app:
        image: mysibsau
        container_name: backend
        env_file: src/.env
        restart: always
        volumes:
            - ./src:/app
            - ./volumes/media:/media
            - ./volumes/static:/static
        depends_on:
            - database
            - migrate
            - collectstatic
        ports:
            - 8000:8000
        command: gunicorn --bind 0.0.0.0:8000 --timeout 600 --log-level debug --reload --max-requests 100 --workers 4 core.wsgi:application


    migrate:
        build: .
        image: mysibsau
        command: python manage.py migrate --noinput
        volumes:
            - ./src:/app
        depends_on: 
            - database

    collectstatic:
        build: .
        image: mysibsau
        command: python manage.py collectstatic --noinput
        volumes:
            - ./src:/app
            - ./volumes/static:/static
        depends_on: 
            - database
            - migrate
