version: "3.8"
services:
    database:
        container_name: mysibsau_database
        image: postgres:13.4-alpine
        restart: always
        env_file: src/.env
        volumes:
            - ./volumes/db/data:/var/lib/database/data

    app:
        build:
            context: .
        container_name: mysibsau_backend
        env_file: src/.env
        restart: always
        volumes:
            - ./src:/app
            - ./volumes/media:/media
            - ./volumes/static:/static
        depends_on:
            - database
        ports: 
            - "127.0.0.1:8000:8000"
        command: bash -c "
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            gunicorn --bind 0.0.0.0:8000
                     --timeout 600
                     --log-level debug
                     --reload
                     --max-requests 100
                     --workers 4 core.wsgi:application"
        labels:
            - traefik.http.routers.mysibsau_backend.rule=Host(`mysibsau.ru`, `timetable.mysibsau.ru`)
            - traefik.http.routers.mysibsau_backend.entrypoints=web

networks:
    default:
        name: traefik_mysibsau
        external: false
