version: "3.8"
services:
    database:
        container_name: database
        image: postgres:13.4-alpine
        restart: always
        env_file: src/.env
        volumes:
            - ./volumes/db/data:/var/lib/database/data

    app:
        build:
            context: .
        container_name: backend
        env_file: src/.env
        restart: always
        volumes:
            - ./src:/app
            - ./volumes/media:/media
            - ./volumes/static:/static
        depends_on:
            - database
        command: bash -c "
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            gunicorn --bind 0.0.0.0:8000 --timeout 600 --log-level debug --reload --max-requests 100 --workers 4 core.wsgi:application"

    nginx:
        container_name: nginx
        image: nginx:1.21.1-alpine
        volumes:
            - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./volumes/static:/static
            - ./volumes/media:/media
        ports:
            - 80:80
        depends_on:
            - app
