# Generated by Django 3.1.6 on 2021-02-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название вакансии')),
                ('company', models.CharField(max_length=128, verbose_name='Компания')),
                ('duties', models.TextField(blank=True, null=True, verbose_name='Обязаности')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Требования')),
                ('conditions', models.TextField(verbose_name='Условия')),
                ('schedule', models.TextField(blank=True, null=True, verbose_name='График работы')),
                ('salary', models.TextField(blank=True, null=True, verbose_name='Зарплата')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('add_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('contacts', models.TextField(verbose_name='Контакты')),
                ('publication_date', models.DateField(verbose_name='Дата публикации')),
                ('hidden', models.BooleanField(default=False, verbose_name='Скрыть')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-publication_date'],
            },
        ),
    ]
