import environ


env = environ.Env()

environ.Env.read_env('../.env')


DEBUG = env.bool('DEBUG', False)
SECRET_KEY = env.str('SECRET_KEY', 'Some-Autogenerated-Secret-Key')

ADMIN_URL = env.str('ADMIN_URL', 'admin/')
SUPERUSERS = env.list('SUPERUSERS')
DEFAULT_PASSWORD = env.str('DEFAULT_PASSWORD', 'password')

DATABASE_HOST = env.str('DATABASE_HOST', '127.0.0.1')
DATABASE_PORT = env.int('DATABASE_PORT', '5432')
DATABASE_NAME = env.str('DATABASE_NAME')
DATABASE_USER = env.str('DATABASE_USER')
DATABASE_PASSWORD = env.str('DATABASE_PASSWORD')

SENTRY = env.bool('SENTRY', False)
DSN = env.str('DSN')

TG_TOKEN = env.str('TG_TOKEN')
TG_DELVELOPER = env.str('TG_DELVELOPER')
