# Generated by Django 3.2.6 on 2021-08-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='institute',
            field=models.CharField(max_length=256, null=True, verbose_name='Институт'),
        ),
    ]
