# Generated by Django 3.1.3 on 2020-11-07 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('id_pallada', models.IntegerField(verbose_name='ID в палладе')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('address', models.TextField(blank=True, verbose_name='Адресс')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='ФИО')),
                ('mail', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('id_pallada', models.IntegerField(verbose_name='ID в палладе')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supgroup', models.IntegerField(verbose_name='Подгруппа')),
                ('lesson_name', models.TextField(verbose_name='Название')),
                ('lesson_type', models.IntegerField(choices=[(1, 'Лекция'), (2, 'Лабораторная работа'), (3, 'Практика')], verbose_name='Тип')),
                ('week', models.IntegerField(choices=[(1, 'Нечетная'), (2, 'Четная')], verbose_name='Неделя')),
                ('day', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День')),
                ('time', models.TextField(verbose_name='Время')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v2.group', verbose_name='Группа')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v2.place', verbose_name='Аудитория')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v2.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Рассписание',
                'verbose_name_plural': 'Рассписание',
            },
        ),
    ]
