# Generated by Django 3.1.3 on 2021-01-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0002_building_department_director_institute_soviet_union'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='coast',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Левый'), (1, 'Правый')], verbose_name='Берег'),
        ),
    ]
