# Generated by Django 3.1.3 on 2021-01-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0008_auto_20210103_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='type',
            field=models.CharField(blank=True, max_length=128, verbose_name='Тип'),
        ),
    ]
