# Generated by Django 3.1.5 on 2021-01-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0011_auto_20210106_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='address_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='building',
            name='address_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='building',
            name='type_en',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='building',
            name='type_ru',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='department',
            name='address_en',
            field=models.TextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='department',
            name='address_ru',
            field=models.TextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='department',
            name='fio_en',
            field=models.CharField(max_length=200, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='department',
            name='fio_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='director',
            name='address_en',
            field=models.TextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='director',
            name='address_ru',
            field=models.TextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='director',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='director',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='institute',
            name='name_en',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='institute',
            name='name_ru',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='institute',
            name='short_name_en',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Сокращенное название'),
        ),
        migrations.AddField(
            model_name='institute',
            name='short_name_ru',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Сокращенное название'),
        ),
        migrations.AddField(
            model_name='soviet',
            name='address_en',
            field=models.TextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='soviet',
            name='address_ru',
            field=models.TextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='soviet',
            name='fio_en',
            field=models.CharField(max_length=200, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='soviet',
            name='fio_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='union',
            name='about_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='union',
            name='about_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='union',
            name='address_en',
            field=models.TextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='union',
            name='address_ru',
            field=models.TextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='union',
            name='fio_en',
            field=models.CharField(max_length=200, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='union',
            name='fio_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='union',
            name='leader_rank_en',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='union',
            name='leader_rank_ru',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='union',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='union',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='union',
            name='short_name_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Сокращенное название'),
        ),
        migrations.AddField(
            model_name='union',
            name='short_name_ru',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Сокращенное название'),
        ),
        migrations.AlterField(
            model_name='union',
            name='page_vk',
            field=models.URLField(blank=True, help_text='Ссылка обязательно должна быть в формате https://vk.com/id1234.\n                       Если она будет иметь другой формат, то нельзя будет отправлять заявки на вступление', null=True, verbose_name='Председатель во вконтакте'),
        ),
    ]
