# Generated by Django 3.1.5 on 2021-01-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0012_auto_20210108_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название кружка')),
                ('fio', models.CharField(max_length=200, verbose_name='Тренер')),
                ('phone', models.CharField(max_length=19, verbose_name='Телефон тренера')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('dates', models.TextField(verbose_name='В какие дни ведет')),
            ],
            options={
                'verbose_name': 'Спортивный кружок',
                'verbose_name_plural': 'Спортивные кружки',
            },
        ),
    ]
