# Generated by Django 3.1.5 on 2021-01-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0015_union_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name'], 'verbose_name': 'Корпус', 'verbose_name_plural': 'Корпуса'},
        ),
        migrations.AlterModelOptions(
            name='union',
            options={'ordering': ['rank'], 'verbose_name': 'Объединениие', 'verbose_name_plural': 'Объединения'},
        ),
    ]
