# Generated by Django 3.1.5 on 2021-01-09 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(editable=False, max_length=64, verbose_name='Автор')),
                ('text', models.TextField(verbose_name='Текст')),
                ('views', models.PositiveIntegerField(default=0, editable=False, verbose_name='Просмотры')),
                ('date_to', models.DateTimeField(auto_now=True, verbose_name='Действует до')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('information_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='informing.information')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='informing/events/', verbose_name='Афиша')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
            bases=('informing.information',),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('information_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='informing.information')),
                ('id_vk', models.PositiveIntegerField(default=0, editable=False, verbose_name='Номер записи в вк')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
            bases=('informing.information',),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512, verbose_name='Текст ссылки')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informing.information')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36, verbose_name='Кто лайкнул')),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informing.information')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='informing/events/', verbose_name='Изображение')),
                ('width', models.PositiveIntegerField(default=0, editable=False)),
                ('height', models.PositiveIntegerField(default=0, editable=False)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informing.news')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
