# Generated by Django 3.1.5 on 2021-01-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informing', '0002_auto_20210109_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='date_to',
            field=models.DateTimeField(verbose_name='Действует до'),
        ),
    ]
