# Generated by Django 3.1.5 on 2021-01-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informing', '0003_auto_20210109_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='informing/news/', verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
