# Generated by Django 3.0.5 on 2020-05-08 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
            },
        ),
        migrations.CreateModel(
            name='Elder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=12, verbose_name='телефон')),
                ('mail', models.EmailField(blank=True, max_length=254, verbose_name='почта')),
            ],
            options={
                'verbose_name': 'Староста',
                'verbose_name_plural': 'Старосты',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='название')),
                ('address', models.TextField(verbose_name='адресс')),
                ('time', models.CharField(max_length=11, verbose_name='время')),
                ('date', models.DateField(verbose_name='дата')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='название')),
                ('mail', models.EmailField(blank=True, max_length=254, verbose_name='почта')),
                ('elder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Elder', verbose_name='староста')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='название')),
                ('view', models.PositiveSmallIntegerField(choices=[(1, 'Лекция'), (2, 'Лабораторная работа'), (3, 'Практика')], verbose_name='тип')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=12, verbose_name='телефон')),
                ('mail', models.EmailField(blank=True, max_length=254, verbose_name='почта')),
                ('department', models.TextField(blank=True, verbose_name='кафедра')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroup', models.IntegerField(default=0, verbose_name='подгруппа')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Cabinet', verbose_name='аудитория')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subject', verbose_name='предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Teacher', verbose_name='преподаватель')),
            ],
            options={
                'verbose_name': 'Подгруппа',
                'verbose_name_plural': 'Подгруппы',
                'ordering': ['subgroup'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=11, verbose_name='время')),
                ('date', models.DateField(verbose_name='дата')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Cabinet', verbose_name='аудитория')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group', verbose_name='группа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subject', verbose_name='предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Teacher', verbose_name='преподаватель')),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=11, verbose_name='время')),
                ('subgroup', models.ManyToManyField(to='api.Subgroup', verbose_name='Подгруппа')),
            ],
            options={
                'verbose_name': 'Лента',
                'verbose_name_plural': 'Ленты',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('even_week', models.BooleanField(verbose_name='четная неделя')),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='день недели')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group', verbose_name='группа')),
                ('lesson', models.ManyToManyField(to='api.Lesson', verbose_name='Лента')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='день недели')),
                ('even_week', models.BooleanField(verbose_name='четная неделя')),
                ('time', models.CharField(max_length=11, verbose_name='время')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Cabinet', verbose_name='аудитория')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Teacher', verbose_name='преподаватель')),
            ],
            options={
                'verbose_name': 'Консультация',
                'verbose_name_plural': 'Консультации',
            },
        ),
    ]
