# Generated by Django 3.0.6 on 2020-08-22 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('mail', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('id_pallada', models.IntegerField(verbose_name='ID в палладе')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=11, verbose_name='Время')),
                ('name', models.TextField(verbose_name='Название')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Лекция'), (2, 'Лабораторная работа'), (3, 'Практика')], verbose_name='Тип')),
                ('teacher', models.TextField(verbose_name='Преподавлатель')),
                ('subgroup', models.IntegerField(verbose_name='Подгруппа')),
                ('place', models.CharField(max_length=7, verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Лента',
                'verbose_name_plural': 'Ленты',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='TimetableGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('even_week', models.BooleanField(verbose_name='Первая неделя')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group', verbose_name='Группа')),
                ('lesson', models.ManyToManyField(to='api.Lesson', verbose_name='Ленты')),
            ],
            options={
                'verbose_name': 'Рассписание группы',
                'verbose_name_plural': 'Рассписание группы',
                'ordering': ['day'],
            },
        ),
    ]
