# Generated by Django 3.0.5 on 2020-05-21 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('mail', models.EmailField(blank=True, max_length=254, verbose_name='почта')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=11, verbose_name='время')),
            ],
            options={
                'verbose_name': 'Лента',
                'verbose_name_plural': 'Ленты',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('phone', models.CharField(blank=True, max_length=12, verbose_name='телефон')),
                ('mail', models.EmailField(blank=True, max_length=254, verbose_name='почта')),
                ('department', models.TextField(blank=True, verbose_name='кафедра')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='название')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Лекция'), (2, 'Лабораторная работа'), (3, 'Практика')], verbose_name='тип')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='TimetableProfessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('even_week', models.BooleanField(verbose_name='четная неделя')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='день недели')),
                ('lesson', models.ManyToManyField(to='api.Lesson', verbose_name='Лента')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Professor', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Рассписание преподавателя',
                'verbose_name_plural': 'Рассписание преподавателя',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='TimetablePlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('even_week', models.BooleanField(verbose_name='четная неделя')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='день недели')),
                ('lesson', models.ManyToManyField(to='api.Lesson', verbose_name='Лента')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Place', verbose_name='кабинет')),
            ],
            options={
                'verbose_name': 'Рассписание кабинета',
                'verbose_name_plural': 'Рассписание кабинета',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='TimetableGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('even_week', models.BooleanField(verbose_name='четная неделя')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='день недели')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group', verbose_name='группа')),
                ('lesson', models.ManyToManyField(to='api.Lesson', verbose_name='Лента')),
            ],
            options={
                'verbose_name': 'Рассписание группы',
                'verbose_name_plural': 'Рассписание группы',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0, verbose_name='подгруппа')),
                ('groups', models.ManyToManyField(to='api.Group', verbose_name='группа')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Place', verbose_name='аудитория')),
                ('professors', models.ManyToManyField(to='api.Professor', verbose_name='преподаватель')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subject', verbose_name='предмет')),
            ],
            options={
                'verbose_name': 'Подгруппа',
                'verbose_name_plural': 'Подгруппы',
                'ordering': ['num'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='subgroup',
            field=models.ManyToManyField(to='api.Subgroup', verbose_name='пара'),
        ),
    ]
