# Generated by Django 3.0.5 on 2020-05-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgroup',
            name='subgroup',
            field=models.IntegerField(default=0, verbose_name='подгруппа'),
        ),
    ]
