# Generated by Django 3.1.3 on 2021-01-01 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coast', models.PositiveSmallIntegerField(verbose_name='Берег')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('link', models.URLField(verbose_name='Ссылка на 2gis')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('address', models.TextField(verbose_name='Адресс')),
                ('phone', models.CharField(max_length=19, verbose_name='Телефон')),
                ('mail', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/campus_sibsau_photos/', verbose_name='Фотография')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('address', models.TextField(verbose_name='Адресс')),
                ('phone', models.CharField(max_length=19, verbose_name='Телефон')),
                ('mail', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Директор института',
                'verbose_name_plural': 'Директора институтов',
            },
        ),
        migrations.CreateModel(
            name='Soviet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/campus_sibsau_photos/', verbose_name='Фотография')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('address', models.TextField(verbose_name='Адресс')),
                ('phone', models.CharField(max_length=19, verbose_name='Телефон')),
                ('mail', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Студенческий совет',
                'verbose_name_plural': 'Студенческие советы',
            },
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='static/campus_sibsau_photos/', verbose_name='Логотип')),
                ('photo', models.ImageField(upload_to='static/campus_sibsau_photos/', verbose_name='Фотография')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('address', models.TextField(verbose_name='Адресс')),
                ('phone', models.CharField(max_length=19, verbose_name='Телефон')),
                ('group_vk', models.URLField(verbose_name='Группа во вконтакте')),
                ('page_vk', models.URLField(verbose_name='Председатель во вконтакте')),
            ],
            options={
                'verbose_name': 'Объединениие',
                'verbose_name_plural': 'Объединения',
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('departments', models.ManyToManyField(to='campus_sibsau.Department', verbose_name='Кафедры')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_sibsau.director', verbose_name='Директор института')),
                ('soviet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_sibsau.soviet', verbose_name='Студенческий совет')),
            ],
            options={
                'verbose_name': 'Институт',
                'verbose_name_plural': 'Институты',
            },
        ),
    ]
