# Generated by Django 3.1.3 on 2021-01-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(upload_to='campus/directors/photos/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='soviet',
            name='image',
            field=models.ImageField(upload_to='campus/soviets/photos/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='union',
            name='logo',
            field=models.ImageField(upload_to='campus/unions/logo/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='union',
            name='photo',
            field=models.ImageField(upload_to='campus/unions/photos', verbose_name='Фотография'),
        ),
    ]
