# Generated by Django 3.1.3 on 2021-01-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0003_auto_20210102_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='department',
            name='phone',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='union',
            name='page_vk',
            field=models.URLField(blank=True, null=True, verbose_name='Председатель во вконтакте'),
        ),
    ]
