# Generated by Django 3.1.3 on 2021-01-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0004_auto_20210102_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soviet',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='soviet',
            name='phone',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='Телефон'),
        ),
    ]
