# Generated by Django 3.1.3 on 2021-01-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0007_auto_20210102_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='union',
            name='about',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='union',
            name='leader_rank',
            field=models.CharField(blank=True, max_length=128, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='union',
            name='short_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Сокращенное название'),
        ),
    ]
