# Generated by Django 3.1.3 on 2021-01-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0010_building_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='union',
            name='page_vk',
            field=models.URLField(blank=True, help_text='Ссылка обязательно должна быть в формате https://vk.com/id1234. \n                       Если она будет иметь другой формат, то нельзя будет отправлять заявки на вступление', null=True, verbose_name='Председатель во вконтакте'),
        ),
    ]
