# Generated by Django 3.1.5 on 2021-01-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0013_sportclub'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportclub',
            name='address_en',
            field=models.TextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='sportclub',
            name='address_ru',
            field=models.TextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='sportclub',
            name='dates_en',
            field=models.TextField(null=True, verbose_name='В какие дни ведет'),
        ),
        migrations.AddField(
            model_name='sportclub',
            name='dates_ru',
            field=models.TextField(null=True, verbose_name='В какие дни ведет'),
        ),
        migrations.AddField(
            model_name='sportclub',
            name='fio_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Тренер'),
        ),
        migrations.AddField(
            model_name='sportclub',
            name='fio_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Тренер'),
        ),
        migrations.AddField(
            model_name='sportclub',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название кружка'),
        ),
        migrations.AddField(
            model_name='sportclub',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название кружка'),
        ),
    ]
