# Generated by Django 3.1.5 on 2021-01-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_reanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='responseoption',
            options={'ordering': ['id'], 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-id'], 'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
    ]
