# Generated by Django 3.1.6 on 2021-02-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informing', '0002_auto_20210207_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'ordering': ['-above', '-id']},
        ),
    ]
