# Generated by Django 3.1.7 on 2021-03-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='file_name',
            field=models.CharField(choices=[('tyz_big.json', 'tyz_big.json')], default='test.json', max_length=64, verbose_name='Файл схемы'),
            preserve_default=False,
        ),
    ]
