# Generated by Django 3.1.7 on 2021-03-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_theatre_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatre',
            name='file_name',
            field=models.CharField(max_length=64, verbose_name='Файл схемы'),
        ),
    ]
