# Generated by Django 3.1.7 on 2021-03-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20210322_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='purchases',
            field=models.ManyToManyField(editable=False, to='tickets.Purchase'),
        ),
    ]
