# Generated by Django 3.1.7 on 2021-03-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_purchases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='purchases',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='tickets',
            field=models.ManyToManyField(related_name='purchase', to='tickets.Ticket', verbose_name='Билеты'),
        ),
    ]
