# Generated by Django 3.1.7 on 2021-03-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20210322_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='count',
        ),
    ]
