# Generated by Django 3.1.7 on 2021-03-07 04:10

import apps.shop.services.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_remove_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('about', models.CharField(blank=True, max_length=512, null=True, verbose_name='Описание')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('code', models.CharField(default=apps.shop.services.utils.generate, max_length=8, verbose_name='Код')),
                ('status', models.IntegerField(choices=[(1, 'Забронирован'), (2, 'Куплен'), (3, 'Отменен')], verbose_name='Статус')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Покупатель', to='user.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Товар', to='shop.product')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
    ]
