# Generated by Django 3.1.7 on 2021-03-07 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210307_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Начало')),
                ('with_place', models.BooleanField(default=True, verbose_name='Билеты с местами')),
                ('hall', models.CharField(max_length=64, verbose_name='Зал')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество билетов')),
            ],
            options={
                'verbose_name': 'Выступление',
                'verbose_name_plural': 'Выступления',
            },
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Театр',
                'verbose_name_plural': 'Театры',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('place', models.PositiveSmallIntegerField(verbose_name='Место')),
                ('row', models.PositiveSmallIntegerField(verbose_name='Ряд')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.concert', verbose_name='Концерт')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('about', models.CharField(max_length=256, verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='shop/theatre/', verbose_name='Афиша')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.theatre', verbose_name='Театр')),
            ],
            options={
                'verbose_name': 'Спектакль',
                'verbose_name_plural': 'Спектакли',
            },
        ),
        migrations.AddField(
            model_name='concert',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.performance', verbose_name='Спектакль'),
        ),
    ]
