# Generated by Django 3.1.7 on 2021-03-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210307_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='concert',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='count',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
