# Generated by Django 3.1.7 on 2021-03-19 05:40

import apps.shop.services.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_name'),
        ('shop', '0004_auto_20210319_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Цена')),
                ('place', models.PositiveSmallIntegerField(verbose_name='Место')),
                ('row', models.PositiveSmallIntegerField(verbose_name='Ряд')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.concert', verbose_name='Концерт')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('code', models.CharField(default=apps.shop.services.utils.generate, max_length=8, verbose_name='Код')),
                ('status', models.IntegerField(choices=[(1, 'Забронирован'), (2, 'Куплен'), (3, 'Отменен')], verbose_name='Статус')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Покупатель', to='user.user')),
                ('tickets', models.ManyToManyField(to='shop.Ticket')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
    ]
