# Generated by Django 3.1.7 on 2021-03-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_purchase_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='count',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='place',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='row',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ряд'),
        ),
    ]
