# Generated by Django 3.1.7 on 2021-03-19 05:49

import apps.shop.services.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_name'),
        ('shop', '0006_auto_20210319_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='code',
            field=models.CharField(default=apps.shop.services.utils.generate, editable=False, max_length=8, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='tickets',
            field=models.ManyToManyField(to='shop.Ticket', verbose_name='Билеты'),
        ),
    ]
