# Generated by Django 3.1.3 on 2021-01-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0005_auto_20210102_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='short_name',
            field=models.CharField(blank=True, max_length=16, verbose_name='Сокращенное название'),
        ),
    ]
