# Generated by Django 3.1.3 on 2021-01-02 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0006_institute_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='departments',
            field=models.ManyToManyField(blank=True, to='campus_sibsau.Department', verbose_name='Кафедры'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='soviet',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='campus_sibsau.soviet', verbose_name='Студенческий совет'),
        ),
    ]
