# Generated by Django 3.1.3 on 2021-01-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0009_building_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='address',
            field=models.CharField(default=None, max_length=256, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
