# Generated by Django 3.1.6 on 2021-02-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0016_auto_20210111_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportclub',
            name='logo',
            field=models.ImageField(blank=True, upload_to='campus/sports/logo', verbose_name='Логотип'),
        ),
    ]
