# Generated by Django 3.1.6 on 2021-02-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0017_sportclub_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportclub',
            name='logo',
            field=models.ImageField(upload_to='campus/sports/logo', verbose_name='Логотип'),
        ),
    ]
