# Generated by Django 3.1.6 on 2021-02-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0018_auto_20210205_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('fio', models.CharField(blank=True, max_length=128, verbose_name='Руководитель')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('about', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Конструкторское бюро',
                'verbose_name_plural': 'Конструкторские бюро',
            },
        ),
    ]
