# Generated by Django 3.1.6 on 2021-02-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_sibsau', '0019_designoffice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designoffice',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='designoffice',
            name='fio',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Руководитель'),
        ),
    ]
