# Generated by Django 3.2.6 on 2021-08-16 02:40

import apps.support.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('slug', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True, verbose_name='Код темы')),
                ('title', models.CharField(max_length=31, verbose_name='Название темы')),
                ('title_ru', models.CharField(max_length=31, null=True, verbose_name='Название темы')),
                ('title_en', models.CharField(max_length=31, null=True, verbose_name='Название темы')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('question_ru', models.TextField(null=True, verbose_name='Вопрос')),
                ('question_en', models.TextField(null=True, verbose_name='Вопрос')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('answer_ru', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('answer_en', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('views', models.PositiveIntegerField(default=0, editable=False, verbose_name='Просмотры')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный')),
                ('theme', models.ForeignKey(default=apps.support.models.Theme.get_default_id, on_delete=django.db.models.deletion.SET_DEFAULT, to='support.theme', verbose_name='Тема')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['-views'],
            },
        ),
    ]
