# Generated by Django 3.2.6 on 2021-08-15 10:56

import apps.support.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0002_faq_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('slug', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True, verbose_name='Код темы')),
                ('title', models.CharField(max_length=31, verbose_name='Название темы')),
                ('title_ru', models.CharField(max_length=31, null=True, verbose_name='Название темы')),
                ('title_en', models.CharField(max_length=31, null=True, verbose_name='Название темы')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.AlterField(
            model_name='faq',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faq',
            name='theme',
            field=models.ForeignKey(default=apps.support.models.Theme.get_default_id, on_delete=django.db.models.deletion.SET_DEFAULT, to='support.theme', verbose_name='Тема'),
        ),
    ]
