# Generated by Django 3.2.6 on 2021-08-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_faq_create_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
    ]
