# Generated by Django 3.2.6 on 2021-08-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_auto_20210815_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='title_en',
            field=models.CharField(max_length=31, null=True, verbose_name='Название темы'),
        ),
        migrations.AddField(
            model_name='theme',
            name='title_ru',
            field=models.CharField(max_length=31, null=True, verbose_name='Название темы'),
        ),
    ]
