# Generated by Django 3.2.1 on 2021-08-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_faq_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичный'),
        ),
    ]
