# Generated by Django 3.2.6 on 2021-08-15 07:18

import apps.support.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_auto_20210815_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='theme',
            field=models.ForeignKey(default=apps.support.models.Theme.get_default_id, on_delete=django.db.models.deletion.SET_DEFAULT, to='support.theme', verbose_name='Тема'),
        ),
    ]
