# Generated by Django 3.1.3 on 2021-01-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='reanswer',
            field=models.BooleanField(default=False, verbose_name='Повторный ответ'),
        ),
    ]
