# Generated by Django 3.1.6 on 2021-02-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='add_info',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='duties',
            field=models.TextField(blank=True, null=True, verbose_name='Обязаности'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.TextField(blank=True, null=True, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='schedule',
            field=models.TextField(blank=True, null=True, verbose_name='График работы'),
        ),
    ]
