# Generated by Django 3.1.6 on 2021-02-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='date_update',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата обновления'),
        ),
    ]
