# Generated by Django 3.1.3 on 2020-12-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date_to',
            field=models.DateTimeField(verbose_name='Действует до'),
        ),
    ]
