# Generated by Django 3.1.3 on 2020-12-28 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='necessarily',
            field=models.BooleanField(default=True, verbose_name='Обязательно ответить'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='responseoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question', verbose_name='Вопрос'),
        ),
    ]
