# Generated by Django 3.1.6 on 2021-02-20 07:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiningRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Столовая',
                'verbose_name_plural': 'Столовые',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип блюда',
                'verbose_name_plural': 'Типы блюд',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('weight', models.CharField(max_length=32, verbose_name='Вес')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('date', models.DateField(default=datetime.date(2021, 2, 20), editable=False, verbose_name='Дата')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.diningroom', verbose_name='Столовая')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.type', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
    ]
