# Generated by Django 3.1.6 on 2021-02-20 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 20, 7, 30, 19, 167216, tzinfo=utc), editable=False, verbose_name='Дата'),
        ),
    ]
