# Generated by Django 3.1.7 on 2021-03-04 02:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20210223_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 2, 25, 0, 148965, tzinfo=utc), editable=False, verbose_name='Дата'),
        ),
    ]
