# Generated by Django 3.0.6 on 2020-08-26 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('mail', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('id_pallada', models.IntegerField(verbose_name='ID в палладе')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='Номер подгруппы')),
                ('name', models.TextField(verbose_name='Название предмета')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Лекция'), (2, 'Лабораторная работа'), (3, 'Практика')], verbose_name='Тип')),
                ('teacher', models.TextField(verbose_name='Преподавлатель')),
                ('place', models.CharField(max_length=7, verbose_name='Кабинет')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Подгруппа',
                'verbose_name_plural': 'Подгруппы',
            },
        ),
        migrations.CreateModel(
            name='TimetableGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('even_week', models.ManyToManyField(related_name='even_week', to='api.Day', verbose_name='Четная неделя')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group', verbose_name='Группа')),
                ('odd_week', models.ManyToManyField(related_name='odd_week', to='api.Day', verbose_name='Нечетная неделя')),
            ],
            options={
                'verbose_name': 'Рассписание группы',
                'verbose_name_plural': 'Рассписание групп',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=11, verbose_name='Время')),
                ('subgroups', models.ManyToManyField(to='api.Subgroup', verbose_name='Подгруппы')),
            ],
            options={
                'verbose_name': 'Лента',
                'verbose_name_plural': 'Ленты',
                'ordering': ['time'],
            },
        ),
        migrations.AddField(
            model_name='day',
            name='lessons',
            field=models.ManyToManyField(to='api.Lesson', verbose_name='Пары'),
        ),
    ]
