# Generated by Django 3.1.3 on 2021-01-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.ImageField(upload_to='events_logo/', verbose_name='Афиша'),
        ),
    ]
