# Generated by Django 3.1.3 on 2021-01-02 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210102_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_to',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Действует до'),
            preserve_default=False,
        ),
    ]
