# Generated by Django 3.1.3 on 2021-01-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_date_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.ImageField(upload_to='events/logo/', verbose_name='Афиша'),
        ),
    ]
