# Generated by Django 3.1.3 on 2021-01-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210102_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.CharField(max_length=200, verbose_name='Автор'),
        ),
    ]
