# Generated by Django 3.1.6 on 2021-02-12 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=16, verbose_name='Токен')),
                ('group', models.CharField(max_length=16, verbose_name='Группа')),
                ('average', models.FloatField(default=5.0, verbose_name='Средний балл')),
                ('creation_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('last_entry', models.DateTimeField(verbose_name='Последняя авторизация')),
                ('banned', models.BooleanField(default=False, verbose_name='Пользователь заблокирован')),
            ],
        ),
    ]
