# Generated by Django 3.2.6 on 2021-08-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='FIO',
            field=models.CharField(default='-', max_length=128, verbose_name='ФИО'),
        ),
    ]
