# Generated by Django 3.1.6 on 2021-02-12 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banned',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
    ]
