# Generated by Django 3.2.6 on 2021-08-27 20:21

from django.db import migrations, models
import django.db.models.deletion


def group_link(apps, schema_editor):
    User = apps.get_model('user', 'User')
    Group = apps.get_model('timetable', 'Group')
    for user in User.objects.all():
        group = Group.objects.filter(name=user.group).first()
        user.group_link = group
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
        ('user', '0002_auto_20210828_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.group', verbose_name='Группа'),
        ),
        migrations.RunPython(group_link),
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='group_link',
            new_name='group',
        ),
    ]
