# Generated by Django 3.1.7 on 2021-03-07 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
