# Generated by Django 3.2.6 on 2021-08-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210827_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fio',
            field=models.CharField(default='-', max_length=150, verbose_name='ФИО'),
        ),
    ]
