# Generated by Django 3.2.6 on 2021-08-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='test', editable=False, max_length=16, verbose_name='Токен'),
            preserve_default=False,
        ),
    ]
