name: update

on:
  schedule:
     - cron:  '0 8 * * *'

jobs:
  update_timetable:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: ${{ secrets.URL_FOR_UPDATE }}
