name: Run tests on any Push event
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Install pipenv
        run: pip install pipenv
      - name: Install requirements
        run: python3 -m pipenv sync
      - name: Run tests
        run: python3 -m pipenv run src/manage.py test
      - name: Tests report
        run: coverage report
