name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@min
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Install pipenv
        run: pip install pipenv
      - name: Install requirements
        run: python3 -m pipenv sync
      - name: Run tests
        run: python3 -m pipenv run src/manage.py test
      - name: Tests report
        run: coverage report
